# Generated by Django 4.1.2 on 2022-12-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_alter_designinfo_design_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='designs.designinfo'),
        ),
    ]
