# Generated by Django 4.1.2 on 2022-12-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.designinfo'),
        ),
    ]
